In [8]:
import pandas as pd
import numpy as np

#dataframe = pd.read_csv('Prueba2.csv', sep=';',encoding ='latin-1')
#print(dataframe)
dataframe = pd.read_csv('Datos.csv', sep=';',encoding ='latin-1')
print(dataframe)

C:\Users\AE5\AppData\Local\Temp\ipykernel_5912\3588273756.py:6: DtypeWarning: Columns (0,1) have mixed types. Specify dtype option on import or set low_memory=False.
  dataframe = pd.read_csv('Datos.csv', sep=';',encoding ='latin-1')


            fecha          hora  temperatura  Humedad Relativa  \
0       01/01/2016  12:00:07 AM       30.017            71.095   
1       01/01/2016  12:01:06 AM       29.989            71.328   
2       01/01/2016  12:02:06 AM       29.983            71.232   
3       01/01/2016  12:03:06 AM       29.921            71.333   
4       01/01/2016  12:04:06 AM       29.860            71.740   
...            ...          ...          ...               ...   
999995         NaN          NaN          NaN               NaN   
999996         NaN          NaN          NaN               NaN   
999997         NaN          NaN          NaN               NaN   
999998         NaN          NaN          NaN               NaN   
999999         NaN          NaN          NaN               NaN   

        PresionAtmosferica  RadiacionSolar  Velocidad  Potencia  
0                  1015.61           0.074      1.703  -36.6627  
1                  1015.61           0.165      0.859  -38.4633  
2        

In [9]:
#X = dataframe.iloc[:, 2:9].values
#y = dataframe.iloc[:, 9].values
#print(y)
dataframe.dropna(inplace=True)
dataframe.isnull().sum().sum()
X = dataframe.iloc[:, 2:7].values
y = dataframe.iloc[:, 7].values

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [11]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

print(X_test)

[[-0.73060999 -1.29215334 -0.23784344 -0.33259576  0.56462383]
 [-0.42121906  0.83523909  0.90425807 -0.93872825 -1.04373651]
 [ 1.15064293  0.5573673  -0.91113473  1.27010992 -0.94641137]
 ...
 [-0.32279013  0.63975504  1.1635999   0.64918482  2.31897187]
 [-0.16794462  0.3937828  -2.87614782  1.64373014  0.41863612]
 [ 1.54645927  0.4421459  -0.76650179 -1.048161    0.52594332]]


In [12]:
#from sklearn.decomposition import PCA
#pca = PCA(n_components = )
#X_train = pca.fit_transform(X_train)
#X_test = pca.transform(X_test)
#print(X_train)

In [13]:
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score

model = linear_model.LinearRegression()
model.fit(X_train, y_train)
#LinearRegression(copy_x=true, fit_intercept=True, n_jobs=None, normalize=False)
y_pred = model.predict(X_test)
print(X_test)

[[-0.73060999 -1.29215334 -0.23784344 -0.33259576  0.56462383]
 [-0.42121906  0.83523909  0.90425807 -0.93872825 -1.04373651]
 [ 1.15064293  0.5573673  -0.91113473  1.27010992 -0.94641137]
 ...
 [-0.32279013  0.63975504  1.1635999   0.64918482  2.31897187]
 [-0.16794462  0.3937828  -2.87614782  1.64373014  0.41863612]
 [ 1.54645927  0.4421459  -0.76650179 -1.048161    0.52594332]]


In [14]:
print('Coefficients:', model.coef_)
print('Intercept:', model.intercept_)
print('Mean squared error (MSE): %.2f'
      % mean_squared_error(y_test, y_pred))
print('Coefficient of determination (R^2): %.2f'
      % r2_score(y_test, y_pred))

Coefficients: [-0.02257745  0.00820935 -0.40815932  0.00150435 -0.01702593]
Intercept: -38.41971724841961
Mean squared error (MSE): 0.20
Coefficient of determination (R^2): 0.45
