In [8]:
import pandas as pd
import numpy as np

#dataframe = pd.read_csv('Prueba2.csv', sep=';',encoding ='latin-1')
dataframe = pd.read_csv('Datos.csv', sep=';',encoding ='latin-1')

print(dataframe)

C:\Users\AE5\AppData\Local\Temp\ipykernel_8944\4038155825.py:5: DtypeWarning: Columns (0,1) have mixed types. Specify dtype option on import or set low_memory=False.
  dataframe = pd.read_csv('Datos.csv', sep=';',encoding ='latin-1')


            fecha          hora  temperatura  Humedad Relativa  \
0       01/01/2016  12:00:07 AM       30.017            71.095   
1       01/01/2016  12:01:06 AM       29.989            71.328   
2       01/01/2016  12:02:06 AM       29.983            71.232   
3       01/01/2016  12:03:06 AM       29.921            71.333   
4       01/01/2016  12:04:06 AM       29.860            71.740   
...            ...          ...          ...               ...   
999995         NaN          NaN          NaN               NaN   
999996         NaN          NaN          NaN               NaN   
999997         NaN          NaN          NaN               NaN   
999998         NaN          NaN          NaN               NaN   
999999         NaN          NaN          NaN               NaN   

        PresionAtmosferica  RadiacionSolar  Velocidad  Potencia  
0                  1015.61           0.074      1.703  -36.6627  
1                  1015.61           0.165      0.859  -38.4633  
2        

In [9]:
dataframe.dropna(inplace=True)
dataframe.isnull().sum().sum()
print(dataframe)
dataframe.dtypes
#X = dataframe.iloc[:, 2:9].values
#y = dataframe.iloc[:, 9].values
X = dataframe.iloc[:, 2:7].values
y = dataframe.iloc[:, 7].values
print(y)

            fecha          hora  temperatura  Humedad Relativa  \
0       01/01/2016  12:00:07 AM       30.017            71.095   
1       01/01/2016  12:01:06 AM       29.989            71.328   
2       01/01/2016  12:02:06 AM       29.983            71.232   
3       01/01/2016  12:03:06 AM       29.921            71.333   
4       01/01/2016  12:04:06 AM       29.860            71.740   
...            ...          ...          ...               ...   
118892  06/23/2016   7:00:09 PM       29.211            63.918   
118893  06/23/2016   8:00:10 PM       28.760            66.897   
118894  06/23/2016   9:00:10 PM       28.158            71.015   
118895  06/23/2016  10:00:10 PM       28.003            72.262   
118896  06/23/2016  11:00:10 PM       27.784            72.638   

        PresionAtmosferica  RadiacionSolar  Velocidad  Potencia  
0                  1015.61           0.074      1.703  -36.6627  
1                  1015.61           0.165      0.859  -38.4633  
2        

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [11]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

print(X_test)

[[-0.73060999 -1.29215334 -0.23784344 -0.33259576  0.56462383]
 [-0.42121906  0.83523909  0.90425807 -0.93872825 -1.04373651]
 [ 1.15064293  0.5573673  -0.91113473  1.27010992 -0.94641137]
 ...
 [-0.32279013  0.63975504  1.1635999   0.64918482  2.31897187]
 [-0.16794462  0.3937828  -2.87614782  1.64373014  0.41863612]
 [ 1.54645927  0.4421459  -0.76650179 -1.048161    0.52594332]]


In [12]:
from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor(n_estimators=100, random_state=0)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
print(y_pred)

[-38.290892 -38.455645 -38.296061 ... -39.397794 -38.068594 -38.066962]


In [14]:
from sklearn import metrics

print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 0.052378373943395555
Mean Squared Error: 0.06710173845958822
Root Mean Squared Error: 0.2590400325424397
