In [12]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

#dataframe = pd.read_csv('Prueba2.csv', sep=';',encoding ='latin-1')
#print(dataframe)
dataframe = pd.read_csv('Datos.csv', sep=';',encoding ='latin-1')
print(dataframe)

            fecha          hora  temperatura  Humedad Relativa  \
0       01/01/2016  12:00:07 AM       30.017            71.095   
1       01/01/2016  12:01:06 AM       29.989            71.328   
2       01/01/2016  12:02:06 AM       29.983            71.232   
3       01/01/2016  12:03:06 AM       29.921            71.333   
4       01/01/2016  12:04:06 AM       29.860            71.740   
...            ...          ...          ...               ...   
999995         NaN          NaN          NaN               NaN   
999996         NaN          NaN          NaN               NaN   
999997         NaN          NaN          NaN               NaN   
999998         NaN          NaN          NaN               NaN   
999999         NaN          NaN          NaN               NaN   

        PresionAtmosferica  RadiacionSolar  Velocidad  Potencia  
0                  1015.61           0.074      1.703  -36.6627  
1                  1015.61           0.165      0.859  -38.4633  
2        

In [13]:
dataframe.dropna(inplace=True)
dataframe.isnull().sum().sum()
X = dataframe.iloc[:, 2:7].values
y = dataframe.iloc[:, 7].values
print(dataframe)

            fecha          hora  temperatura  Humedad Relativa  \
0       01/01/2016  12:00:07 AM       30.017            71.095   
1       01/01/2016  12:01:06 AM       29.989            71.328   
2       01/01/2016  12:02:06 AM       29.983            71.232   
3       01/01/2016  12:03:06 AM       29.921            71.333   
4       01/01/2016  12:04:06 AM       29.860            71.740   
...            ...          ...          ...               ...   
118892  06/23/2016   7:00:09 PM       29.211            63.918   
118893  06/23/2016   8:00:10 PM       28.760            66.897   
118894  06/23/2016   9:00:10 PM       28.158            71.015   
118895  06/23/2016  10:00:10 PM       28.003            72.262   
118896  06/23/2016  11:00:10 PM       27.784            72.638   

        PresionAtmosferica  RadiacionSolar  Velocidad  Potencia  
0                  1015.61           0.074      1.703  -36.6627  
1                  1015.61           0.165      0.859  -38.4633  
2        

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [15]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

print(X_test)

[[-0.73060999 -1.29215334 -0.23784344 -0.33259576  0.56462383]
 [-0.42121906  0.83523909  0.90425807 -0.93872825 -1.04373651]
 [ 1.15064293  0.5573673  -0.91113473  1.27010992 -0.94641137]
 ...
 [-0.32279013  0.63975504  1.1635999   0.64918482  2.31897187]
 [-0.16794462  0.3937828  -2.87614782  1.64373014  0.41863612]
 [ 1.54645927  0.4421459  -0.76650179 -1.048161    0.52594332]]


In [16]:
from xgboost import XGBRegressor 
xg_reg = XGBRegressor()
xg_reg.fit(X_train, y_train)
y_pred_xg = xg_reg.predict(X_test)

In [49]:
mse = mean_squared_error(y_test,y_pred_xg)
rmse = np.sqrt(mse)
print("RSME: %0.2f" % (rmse))
mse

RSME: 0.27


0.0710409810204717

In [48]:
from sklearn.metrics import mean_squared_error
mse_rf = np.round(mean_squared_error(y_test, y_pred_xg), 2)
mse_rf

0.07

In [ ]:
from sklearn.metrics import mean_squared_error
mse_rf = np.round(mean_squared_error(y_test, y_train), 2)
mse_rf